version: "3"

services:
  postgres:
    container_name: postgres_contacts_app
    image: postgres:16.1
    environment:
      POSTGRES_DB: contacts_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis_contacts_app
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
